[build]
  command = "npm run build"
  publish = ".next"
  base = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configure build environment
[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Force Netlify to recognize the app directory
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Explicitly set the app directory path
[build.processing]
  skip_processing = false